### ISSUE TITLE
erro durante compile

### ISSUE THREAD

**Issue by marcelowu** [mundipagg/magento2#1]
Compilation was started.

Details:

`Proxies code generation... 0/7 [>---------------------------]   0% 1 sec 40.0 MiProxies code generation... 1/7 [====>-----------------------]  14% 2 secs 44.0 MRepositories code generation... 1/7 [====>-----------------------]  14% 2 secs 4Repositories code generation... 2/7 [========>-------------------]  28% 2 mins 1Service data attributes generation... 2/7 [========>-------------------]  28% 2 Service data attributes generation... 3/7 [============>---------------]  42% 2 Application code generator... 3/7 [============>---------------]  42% 2 mins 138Application code generator... 4/7 [================>-----------]  57% 2 mins 158Interceptors generation... 4/7 [================>-----------]  57% 2 mins 158.0 Interceptors generation... 5/7 [====================>-------]  71% 3 mins 176.0 Area configuration aggregation... 5/7 [====================>-------]  71% 3 mins 176.0 MiB`

` [ReflectionException]
  Class MundiPagg\MundiPagg\Gateway\Transaction\TwoCreditCard\Resource\Refund
  \CreditCardTransaction does not exist`

**Comment by ThiagoBarradas** [comment]
Hey, this issue has been fixed in current version, please, update our module.
