### ISSUE TITLE
erro no arredontamento de taxa de juros..

### ISSUE THREAD

**Issue by marcelowu** [mundipagg/magento2#11]

**Comment by marcelowu** [comment]
sem juros esta ok. mas com juros ta erro..

![screenshot_20180804-152902](https://user-images.githubusercontent.com/30912144/43679432-9444156c-97fb-11e8-8e6d-b55a0fea037c.jpg)

**Comment by marcelowu** [comment]
![sem titulo](https://user-images.githubusercontent.com/30912144/43973479-08d61cf2-9cae-11e8-8326-c0d5a0effd19.png)

**Comment by michelpl** [comment]
Olá @marcelowu!
O primeiro problema você já deve ter relacionado ao valor inválido para transações de simulador, já o erro no arredondamento foi identificado e será corrigido.
Trata-se de um problema de exibição, o preço final do pedido está correto. (2098,00 + 9,5% = 2297,31)

Assim que possível, subiremos uma versão com esta correção.

**Comment by michelpl** [comment]
Issue resolvida à partir da versão 1.2.30
