### ISSUE TITLE
ERROR 404 - PAYMENTCONDITIONS

### ISSUE THREAD

**Issue by daniloleonecarneiro** [mundipagg/magento2#119]
Pessoal, boa tarde.

Qual o motivo deste problema?

![image](https://user-images.githubusercontent.com/36852522/61649149-433acc00-ac87-11e9-8111-1171c40bc6c1.png)

**Comment by GabrielDeveloper** [comment]
@daniloleonecarneiro boa tarde, não temos evidencias suficiente para analisar o caso, favor entre em contato com o nosso canal de atendimento enviando mais informações. suporte@mundipagg.com

**Comment by daniloleonecarneiro** [comment]
Certo. Vou aproveitar e enviar outros pontos.

**Comment by michelpl** [comment]
Olá @daniloleonecarneiro ! Conseguiu entrar em contato com nosso canal de atendimento? Vamos fechar a issue por aqui.
