### ISSUE TITLE
erro arredontamento de parcela do primeiro cartao

### ISSUE THREAD

**Issue by marcelowu** [mundipagg/magento2#12]
PRIMEIRO CARTAO:
"amount": 5193765, (*AQUI PARA SE 5193)
        "status": "not_authorized",
        "success": false,
        "installments": 4,

SEGUNDO CARTAO:

 "amount": 2110,
        "status": "authorized_pending_capture",
        "success": true,
        "installments": 4,

**Comment by michelpl** [comment]
@marcelowu pode dar mais informações sobre o problema? Ele ainda está acontecendo na versão mais recente do módulo?

**Comment by michelpl** [comment]
Fechando issue por falta de resposta
