### ISSUE TITLE
adicinar máscara e validação de CNPJ, CPF no magento2

### ISSUE THREAD

**Issue by wubuyun** [mundipagg/magento2#13]
Excelente código para Máscara e Validação de CNPJ, CPF, CEP Data e Telefone
[http://www.fabiobmed.com.br/excelente-codigo-para-mascara-e-validacao-de-cnpj-cpf-cep-data-e-telefone/](http://www.fabiobmed.com.br/excelente-codigo-para-mascara-e-validacao-de-cnpj-cpf-cep-data-e-telefone/)
exemplo no pagseguro/magento2
[https://github.com/pagseguro/magento2/blob/bb6e6ea4398c4357af5711d9b3b48d44765aa134/view/frontend/web/js/model/direct-payment-validator.js](https://github.com/pagseguro/magento2/blob/bb6e6ea4398c4357af5711d9b3b48d44765aa134/view/frontend/web/js/model/direct-payment-validator.js)

**Comment by michelpl** [comment]
Olá @wubuyun!
Obrigado pela contribuição!
O tratamento dos campos referentes ao cadastro do cliente não cabe a módulos de pagamento (ao menos que o módulo não utilize o cadastro padrão do Magento).
