### ISSUE TITLE
Sobre a recorrencia

### ISSUE THREAD

**Issue by texboy** [mundipagg/magento2#156]
### Recorrência

Opa! Estou precisando de algumas informações pra fechar o escopo de um projeto e eu gostaria caso possível de saber essas informações abaixo.

- Existe algum prazo para essa feature ser lançada na branch principal? 
- O desenvolvimento dessa funcionalidade está sendo finalizada?

**Comment by michelpl** [comment]
Oi @texboy. Ainda não temos prazo para entrega da recorrência. Ela está sendo desenvolvida para atender a um cenário específico primeiramente para depois ganhar a abrangência de mais cenários.
