### ISSUE TITLE
Erro com versõe do PHP

### ISSUE THREAD

**Issue by wgbn** [mundipagg/magento2#16]
### Status

BUG REPORT

### Expected behaviour

Instalar Via Composer

### Actual behaviour

Nos requisitos do módulo estão especificados as versões mínimas do PHP como sendo >= 5.6
Meu sistema tem o PHP 7.2.12 e recebo a mensagem do composer:
Package mundipagg/mundipagg-magento2-module at version  has a PHP requirement incompatible with your PHP version (7.2.12)

### Environment

- PHP 7.2.12
Magento 2.3.0

### Logs / Stack trace

```
Package mundipagg/mundipagg-magento2-module at version  has a PHP requirement incompatible with your PHP version (7.2.12)
```

**Comment by michelpl** [comment]
Olá @wgbn!
Estamos verificando a compatibilidade com essa versão do php. 
Assim que possível, daremos retorno.

**Comment by michelpl** [comment]
Issue resolvida
