### ISSUE TITLE
Voucher Payment

### ISSUE THREAD

**Issue by fhferreira** [mundipagg/magento2#198]
É possível receber por meio de vouchers utilizando o módulo? VR/SODEXO

**Comment by michelpl** [comment]
Oi @fhferreira 
Ainda não possuímos voucher no módulo.
Estamos trabalhando para entregar essa feature, mas ainda não temos uma data definida.

**Comment by fhferreira** [comment]
Obrigado @michelpl fico no aguarde então, tenho um amigo que está interessado em utilizar essa modalidade.

**Comment by michelpl** [comment]
@fhferreira você já consegue utilizar o voucher na versão 2.1.2-beta.
Trata-se de uma versão beta com essa outras features importantes que ainda vai ser lançada como principal, mas já possui alguns clientes testando desde a 2.0.0-beta

**Comment by fhferreira** [comment]
Obrigado @michelpl vou ver se consigo testar.
