### ISSUE TITLE
D+1 identificando feriados e finais de semanas 

### ISSUE THREAD

**Issue by rafagaseo** [mundipagg/magento2#209]
No módulo atual caso o cliente compre na sexta com boleto, o boleto terá seu vencimento no sábado. 

A sugestão é o módulo reconhecer automaticamente sábado e domingo e permitir adicionar os feriados  pulando a data do vencimento.

**Comment by michelpl** [comment]
Olá @rafagaseo ! Tudo bem?
Obrigado pela sugestão, porém temos diversas features importantes que ainda estão sendo desenvolvidas no nosso módulo e por isso não temos como dar prioridade para essa demanda no momento.
De qualquer forma, qualquer boleto que vença em um fim de semana ou feriado, pode ser pago no primeiro dia útil a seguir.

Abs

**Comment by michelpl** [comment]
Olá novamente @rafagaseo!
Entrei em contato como time da api e eles me informaram que isso é possível fazer através de uma configuração na conta do cliente.
"Para utilizar a funcionalidade Contagem em dias úteis para vencimento de boleto, o lojista deverá enviar um e-mail para suporte@mundipagg.com com a solicitação"

Abs
