### ISSUE TITLE
Problema ao adicionar produtos com quantidade maior que 1 ao carrinho

### ISSUE THREAD

**Issue by cayohenrique** [mundipagg/magento2#230]
Olá, 
Usando a versão "2.*@beta" notei um erro quando tenho o campo de quantidade ao adicionar o produto ao carrinho.

Na classe JustOneProductPlanInCart, o código está apenas verificando a quantidade do produto e não se existe um plan no carrinho.
Eu estou adicionando um produto normal e está dando erro. 
Eu dei um improve na condição para funcionar mas recomendo alguem olhar isso.
Atual:
`if ($currentProduct->getQuantity() > 1) {
            $this->error = $this->i18n->getDashboard(
                'You must have only one product plan in the cart'
            );
        }`

Minha correção:
`if (!empty($productListInCart->getProductsPlan()) && $currentProduct->getQuantity() > 1) {
            $this->error = $this->i18n->getDashboard(
                'You must have only one product plan in the cart'
            );
        }`

**Comment by GabrielDeveloper** [comment]
@cayohenrique Obrigado pelo report.

Já estamos trabalhando nessa correção.

**Comment by GabrielDeveloper** [comment]
@cayohenrique o erro foi corrigido, favor atualize para a nova versão:

https://github.com/mundipagg/magento2/releases/tag/2.1.2-beta

Obrigado!
