### ISSUE TITLE
Voucher Alelo e Voucher Sodexo

### ISSUE THREAD

**Issue by cayohenrique** [mundipagg/magento2#242]
Testei os dois Vouchers em produção (alelo e sodexo) e os dois estão com erro na versão beta 2.2.0. 

Sodexo está com problema para validar o installments. Verifiquei que isso ocorre no arquivo AbstractCreditCardPayment.php na linha 81
`        $this->validateIfIsRealInstallment($installments);
`

Alelo está com problema de bandeira. O campo cc_type muda para "aura" quando eu coloco um cartão Alelo válido. Então não sei se ele está com o problema problema do Sodexo porque para antes. 

tem como verificarem por favor?

**Comment by GabrielDeveloper** [comment]
@cayohenrique Obrigado pelo report, já estamos verificando e trabalhando nas correções!
