### ISSUE TITLE
Erro criação de pedido pelo Admin

### ISSUE THREAD

**Issue by cayohenrique** [mundipagg/magento2#248]
Olá pessoal, tudo bem?
Achei um problema com o módulo na hora de criar um pedido pelo admin.
Creio que o módulo de vocês não deve permitir mesmo criação usando ele via admin mas tem uma parte que está travando os outros métodos de pagamento. 
No arquivo **PaymentMethodAvailable.php** a function **getRecurrenceProducts** está retornando um erro quando vou criar um pedido pelo admin. 

_Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /vendor/mundipagg/mundipagg-magento2-module/Observer/PaymentMethodAvailable.php on line 143_

Eu adicionei apenas uma verificação na variável $items e resolveu.

Podem verificar? 

Obrigado!

**Comment by GabrielDeveloper** [comment]
Bom dia @cadohr tudo tranquilo?!

Este erro resolvemos na versão 2.1.2-beta, você pode conferir por favor?

Aqui está exatamente o commit que fizemos:

https://github.com/mundipagg/magento2/commit/4f60625e4382d505f9326d4af0ab86a2dc21f504#diff-a127444fd49c1f7b872699144abea3f5

Muito obrigado pelos reports!

**Comment by cayohenrique** [comment]
Vi aqui. Valeu!
