### ISSUE TITLE
Erro ao editar cliente no admin

### ISSUE THREAD

**Issue by cayohenrique** [mundipagg/magento2#249]
Quando vou editar um cliente no admin e existe alguma exception (ele não preencheu o CPF por exemplo), o código cai no Exception do file **AdminCustomerBeforeSave.php**.

O problema é que no catch da linha 48, tem esse código:
`            $log->info(print_r($exception->errors, true));
`
que retorna o seguinte erro nos logs
_main.CRITICAL: Exception message: Notice: Undefined property: Exception::$errors in vendor/mundipagg/mundipagg-magento2-module/Observer/AdminCustomerBeforeSave.php on line 51_

Quando substitui esse `$exception->errors` por `$exception->getMessage()`, por exemplo, funciona.

Podem verificar por favor?

**Comment by GabrielDeveloper** [comment]
@cayohenrique  obrigado pelo report, já estamos verificando. 
Assim que lançar a correção aviso aqui!

Obrigado!

**Comment by GabrielDeveloper** [comment]
@cayohenrique esqueci de te avisar da versão, mas ja esta em produção a correção deste erro:

https://github.com/mundipagg/magento2/releases

Obrigado novamente pelo report!

**Comment by cayohenrique** [comment]
Boa! Fechando a issue!

**Comment by cayohenrique** [comment]
Obrigado!
