### ISSUE TITLE
HolderDocumentNumber is Required

### ISSUE THREAD

**Issue by cayohenrique** [mundipagg/magento2#254]
Olá,
Estou usando a versão  2.2.4-beta do módulo e estou com problemas no Voucher.
Os erros anteriores sumiram mas agora ele dá o seguinte erro no dash da mundipagg:

_HolderDocumentNumber is Required_

Quando olho no log, o "document" está preenchido mas o "holder_document" realmente está vazio. 

Estou testando com cartões reais da VR e Sodexo. 

Outra coisa que reparei é que aparentemente o Voucher está usando o file **CreateCreditCardPaymentRequest** ao invés do **CreateVoucherPaymentRequest**
Mudei coisas nos dois e somente apareceu no voucher quando utilizei o **CreateCreditCardPaymentRequest**

Obrigado!

**Comment by GabrielDeveloper** [comment]
@cayohenrique Boa tarde,

Agradeço pelo report, estamos verificando este erro.

Obrigado!

**Comment by wallaceSF** [comment]
@cayohenrique , Boa tarde.

Já atualizamos o módulo adicionando o **HolderDocumentNumber**.

Teria como atualizar a versão do seu módulo por favor.
https://github.com/mundipagg/magento2/releases/tag/2.3.5-beta

Novamente o agradeço pelo report. Qualquer problema encontrado entre em contato.
