### ISSUE TITLE
Venda não finaliza no cartão de crédito

### ISSUE THREAD

**Issue by gabrielhaase** [mundipagg/magento2#261]
Olá, boa tarde.
Estamos utilizando a versão BETA do módulo pois precisamos da funcionalidade de recorrência, porém ao tentar finalizar a compra usando CARTÃO DE CRÉDITO, após preencher os dados referentes ao cartão e clicar no botão para "FINALIZAR A COMPRA" uma mensagem é apresentada informando "BANDEIRA INVÁLIDA" e a venda não conclui.

O teste usando o BOLETO BANCÀRIO está funcionando corretamente.

Poderiam nos ajudar?

Obrigado!

**Comment by michelpl** [comment]
Olá @gabrielhaase !
Respondemos sua solicitação via suporte.
Faltou habilitar as bandeiras de cartão que você quer utilizar e cadastrar seu domínio no dash da Mundipagg
