### ISSUE TITLE
Implementação de algumas informações adicionais no campo additional_information

### ISSUE THREAD

**Issue by guidoac** [mundipagg/magento2#273]
### Tags

BUG REPORT

### Descrição

Durante o desenvolvimento de um projeto, precisamos implementar algumas informações adicionais no retorno da API orders do magento, informações referentes a forma de pagamento Boleto e Cartão de crédito.
No caso, verificamos que podemos utilizar o campo `additional_information` da tabela `sales_order_payment` para armazenar essas informações adicionais que são retornadas pela API da mundipagg.

### O que tentamos fazer para implementar a melhoria

Verificamos o código responsável no módulo em comunicar com a API da mundipagg, encontramos o trecho de código que provavelmente adiciona essas informações no campo Additional Information.
No diretório `vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/Billet/ResourceGateway/Create/Response/GeneralHandler.php` (nesse caso, o Handler para a forma de pagamento Boleto), na função `_handle`, existe o seguinte código como padrão (na versão 2.4 beta do módulo)
`$boletoUrl = $response->charges[0]->lastTransaction->pdf;
$payment->setAdditionalInformation('billet_url', $boletoUrl);`

Contudo, no campo `additional_information` da tabela `sales_order_payment`, não existe esse campo `billet_url` criado.
Também seguimos esse padrão para inserir as outras informações que necessitamos, porém esses campos também não foram armazenados no campo na tabela.

**Comment by GabrielDeveloper** [comment]
Boa tarde @guidoac 

Recentemente implementamos algumas outras informações de boleto e cartão como NSU, TID e numero do boleto neste campo de `additional_informations`  #268 .

Você pode entrar em contato com nosso suporte (suporte@mundipagg.com) solicitando as mudanças que deseja ou abrir um Pull Request que nosso time irá analisar.
