### ISSUE TITLE
Recurso de salvamento de cartão de crédito no perfil do cliente

### ISSUE THREAD

**Issue by guidoac** [mundipagg/magento2#289]
### Tags
SAVED CREDIT CARDS

### Descrição

Recentemente, a loja que atendemos e possuem o módulo da mundipagg para gerenciar os pagamentos solicitou a implementação de um menu onde posso verificar os cartões de créditos salvos pelo usuário (cartões que já foram usados em uma compra), precisamos implementar esse recurso no site.

### O que tentamos fazer para implementar o recurso

Bom, verifiquei nas configurações do módulo da Mundipagg, onde possui uma opção Enable Saved Credit-Cards, ativei esta opção. Logo, reindexei o magento e limpei a cache, caso isso seja algum obstáculo para implementar a alteração de fato.
Fiz uma compra de teste no site, onde utilizei o cartão de crédito conforme descrito no Cenário 1 do simulador de cartões [https://docs.mundipagg.com/docs/simulador-de-cartão-de-crédito](url).
Fiz esse teste e conferi nas tabelas `mundipagg_mundipagg_cards` e `mundipagg_module_core_saved_card`, contudo a tabela continua zerada.

Na loja, utilizamos a versão 2.3.3 do Magento.

Gostaria de saber, preciso fazer alguma outra configuração no módulo para este recurso funcionar? Ocorre o salvamento do cartão normalmente quando utilizo o simulador de cartões?

**Comment by GabrielDeveloper** [comment]
Boa tarde @guidoac , a tabela que salvamos é realmente a `mundipagg_module_core_saved_card` porém fazemos uma verificação antes e só salvamos o cartão após a captura do pedido.

Pode confirmar se este pedido está capturado?

O problema persistindo você consegue entrar em contato pelo suporte@mundipagg.com que iremos pedir alguns dados para que possamos analisar melhor o seu caso, por favor.

**Comment by guidoac** [comment]
Boa noite @GabrielDeveloper , verifiquei na tabela `mundipagg_module_core_transaction` conforme solicitado.
Fiz 3 testes hoje durante o dia, com o simulador de cartões, segue print da tabela citada:

![image](https://user-images.githubusercontent.com/28743974/96933821-8a6dc900-1497-11eb-9bc7-6fe9bd48efd3.png)

Segue print da opção ativada no painel do magento:

![image](https://user-images.githubusercontent.com/28743974/96933869-a83b2e00-1497-11eb-9780-524ff229e183.png)

Caso prefira, posso mandar essa mesma mensagem pelo email.

**Comment by guidoac** [comment]
E agradeço muito pelo rápido retorno!

**Comment by GabrielDeveloper** [comment]
Pode enviar por email por favor para suporte@mundipagg.com pois iremos precisar de dados sensiveis para analisar, como os logs e dados da conta.

Estou fechando essa issue mas aguardo o email para abrirmos um case interno para essa verificação.

Desde ja agradeço!
